# Generated by Django 4.2 on 2024-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='myrat', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='Atayew', max_length=255),
        ),
    ]
